### ISSUE TITLE
DI for nested services

### ISSUE THREAD

**Issue by noamknispel** [WisePricer/quadro#128]
According the docs & example app when you create nested service it'll be available in `nested:service`. This format is understandable when you call your service directly from the container but not when you need to inject it. 
```js
constructor(nested:service) { ... } // => Won't work
```

The suggested solution is get rid of the full path of a service, and call it by his unique name. Nested directory structure should be available only for good look and maintainability reasons.

**Comment by igorshapiro** [comment]
Duplicate of #115
