### ISSUE TITLE
v0.7 - tracking issue

### ISSUE THREAD

**Issue by igorshapiro** [WisePricer/quadro#175]
- [x] Quadro core 
  - [x] Addons loader ( #174 )
- [ ] Quadro test
- [ ] Quadro http server
- [ ] Quadro pubsub
- [ ] Quadro odbm

# Plugins functionality

### Quadro

Includes IoC, Config, Logging, Errors and Addons loader.

### Quadro test

Includes ESLint, mocha, QT namespace, etc.

### Quadro-pubsub

Includes SH pull model (with forwarder), SH push model

### Quadro-odbm

Includes activerecord, model, mongo adapter

**Comment by tomeresk** [comment]
👍

**Comment by dkvasnicka** [comment]
Irrelevant.
