### ISSUE TITLE
Evaluate switching from Koa to Fastify

### ISSUE THREAD

**Issue by tomeresk** [WisePricer/quadro#204]
https://github.com/fastify/fastify

Their [benchmarks](https://github.com/fastify/fastify#benchmarks) claim it is 50% faster than koa when using koa-router (and koa itself is faster than all the other popular web servers/frameworks).

Fastify itself supports async/await and routing and seems to be decently convenient to use.
Also has optional [JSON Schema](http://json-schema.org/) support to possibly make heavily used APIs/handlers faster.

This will likely be a breaking change, though that can possibly be prevented by Quadro intervening to enforce the existing koa API and internally converting it to the Fastify API (I don't think thats a good idea though).

The main discussion I want to raise here is whether this performance increase is big enough to warrant evaluating the feasibility/effort of making this change

**Comment by tomeresk** [comment]
I think this likely won't make a big impact in most cases, since most of the time spent handling the request is not related to koa itself.
It will probably make a noticeable difference in the simple GET APIs (which we are hitting a lot), but I don't think those APIs have a significant impact on server performance at this point.

**Comment by dkvasnicka** [comment]
Router/web framework performance is a complete non-issue in Wiser apps at this point. Fastify might be useful for us as we evolve Quadro (TS support, JSON Schema) but that would be covered in a different task.
