### ISSUE TITLE
Custom routes not working

### ISSUE THREAD

**Issue by RazDarzi** [WisePricer/quadro#94]
Attempting to use the koa router through the supplied router by calling "router.verb()"
 in order to define new route returns : "Error: post `'some url' `middleware` must be a function, not `undefined`".
The custom routes are  batch post requests.

**Comment by RazDarzi** [comment]
console.log indeed prints the module's content

**Comment by igorshapiro** [comment]
It does work as illustrated in https://github.com/WisePricer/quadro/pull/95
